### ISSUE TITLE
APP認証プラグインを無効化した状態で、二段階認証にAPPが表示される

### ISSUE THREAD

**Issue by dotani1111** [EC-CUBE/TwoFactorAuthCustomer42#12]
![image](https://user-images.githubusercontent.com/121000728/223916173-77099912-ed07-4291-99be-3deb728f637a.png)

![image](https://user-images.githubusercontent.com/121000728/223894162-ab23b3fe-a1f7-4f45-8ff6-e9748895a808.png)

ちなみに、選択するとSymfonyエラーが表示されます。
`Unable to generate a URL for the named route "plg_customer_2fa_app_create" as such route does not exist.`
`AbstractController->redirectToRoute('plg_customer_2fa_app_create')
in [app/Plugin/TwoFactorAuthCustomer42/Controller/TwoFactorAuthCustomerController.php ](https://tfa-cube.sai-net.work/_profiler/open?file=app/Plugin/TwoFactorAuthCustomer42/Controller/TwoFactorAuthCustomerController.php&line=229#line229)(line 229)
                // 2段階認証を有効に更新                $Customer->setTwoFactorAuth(true);                $this->entityManager->persist($Customer);                $this->entityManager->flush();                // 初回認証を実施                return $this->redirectToRoute($TwoFactorAuthType->getRoute());            } else {                $error = trans('front.2fa.onetime.invalid_message__reinput');            }        }`

**Comment by KenTanaka** [comment]
無効化時に「認証方式」マスタのレコードが有効状態で残存している為。

・「認証方式」マスタに有効・無効のフラグを追加

■プラグイン　有効・無効
・プラグイン有効化時、レコードをアクティブに変更
・プラグイン無効化時、レコードをディアクティブに変更

■初期設定画面
・初期設定画面にはアクティブな認証方式のみ表示

■（課題）二段階認証
TODO ・SMSで初期設定 / SMSプラグイン無効化した場合 かつ 二段階認証=ONの場合 > 常にログアウトさせる？
 (二段階認証そのものを停止する場合、店舗管理>二段階認証 = OFFで対応可能）

■（課題）会員管理画面
TODO ・二段階認証方式 > 空欄で表示？
(この状態で会員情報を編集した場合、二段階認証方式が初期化されてしまう。）

**Comment by chihiro-adachi** [comment]
修正確認しました
