### ISSUE TITLE
SMS認証でワンタイムトークンが平文保持されているが問題ない？

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/TwoFactorAuthCustomer42#13]
生成したトークンが、DBには平文で保持されている
トークン自体はランダム生成されており、有効期限も合わせて確認することからリスクは低いかと思いましたが念の為

https://github.com/EC-CUBE/TwoFactorAuthCustomer42/blob/067995631fb7da0233535f2caeff7eef2062820f/Controller/TwoFactorAuthCustomerController.php#L284

**Comment by KenTanaka** [comment]
@chihiro-adachi 
パスワードと同等とした方が仕様としては正しい気がしますね。
短い期間のものではあると思いますが、一時的にでも保存はしている為。

**Comment by chihiro-adachi** [comment]
ありがとうございます、修正確認しました。
