### ISSUE TITLE
マイページ配下のページを重要操作ルーティングに指定しても、再認証されていない

### ISSUE THREAD

**Issue by KenTanaka** [EC-CUBE/TwoFactorAuthCustomer42#14]
1. プラグイン設定 > 重要操作ルーティングに mypage_changeを指定
2. フロントで会員ログイン（ログイン時の二段階認証実行）
3. マイページタブの会員情報編集をクリック
　→ 重要操作ルーティングに指定している為、再認証を行う必要があるが、実行されていない

認証Cookieの評価順の見直しが必要。

**Comment by chihiro-adachi** [comment]
修正確認しました
