### ISSUE TITLE
TwilioのAuthトークンをマスキングしたい

### ISSUE THREAD

**Issue by dotani1111** [EC-CUBE/TwoFactorAuthCustomer42#19]
現在、EC-CUBEのAuthトークン設定部分は、そのまま表示されています。

<img width="528" alt="スクリーンショット 2023-03-14 15 55 43" src="https://user-images.githubusercontent.com/121000728/224919890-43c4e900-7e39-464c-bc38-7e22a4ece2bd.png">

TwilioのConsoleではマスキングされているのですが、如何でしょうか？
<img width="599" alt="スクリーンショット 2023-03-14 16 06 26" src="https://user-images.githubusercontent.com/121000728/224922187-a80416f0-693b-41e8-918f-7cc82b538948.png">

**Comment by KenTanaka** [comment]
@chihiro-adachi @dotani1111 
CUBE標準方式でマスキングしました。

**Comment by dotani1111** [comment]
@KenTanaka 
ありがとうございます。
