### ISSUE TITLE
スマホのみでアプリ認証を完結できるようにしたい

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/TwoFactorAuthCustomer42#25]
スマホ1台だけだと、QRコードのスキャンをして設定完了することができない

以下のように、セットアップキーも合わせて表示させておくことで、コピーアンドペーストで設定できる。
https://www.wealthnavi.com/security/mfa/detail2

**Comment by KenTanaka** [comment]
@chihiro-adachi

**Comment by KenTanaka** [comment]
@chihiro-adachi 
要素としては
　・セットアップキー
　・コピー用のボタン or リンク
のような形でtwigに追加します。

![EC-CUBE-SHOP-アプリ認証初期設定・トークン入力 (1)](https://user-images.githubusercontent.com/586502/226221686-65c27fcd-3afe-499c-a3ef-c012f233ea45.png)
![EC-CUBE-SHOP-アプリ認証初期設定・トークン入力 (2)](https://user-images.githubusercontent.com/586502/226221691-1bdb0c3d-6f28-48f3-abc8-0f8863d36c2b.png)

**Comment by chihiro-adachi** [comment]
@KenTanaka
キーのコピーが動作しないようです。
以下のエラーが表示されていました
```
Uncaught (in promise) DOMException: Document is not focused
```

**Comment by KenTanaka** [comment]
確認します。

**Comment by chihiro-adachi** [comment]
セットアップキーを利用して認証アプリへの登録は問題ありません。

**Comment by KenTanaka** [comment]
@chihiro-adachi 
alertではなく、標準モーダルの表現に変更しました。
jsコンソール上でもエラーはありません。

![クリップボードコピー後](https://user-images.githubusercontent.com/586502/227103441-7aeea50b-5f4f-4552-92f3-f20610db813c.png)

**Comment by chihiro-adachi** [comment]
修正確認しました。
