### ISSUE TITLE
「二段階認証機能」という項目名を変更したい

### ISSUE THREAD

**Issue by dotani1111** [EC-CUBE/TwoFactorAuthCustomer42#32]
現在、本会員時にも、2段階認証が行われております。
それにより「二段階認証機能」という項目名が、少々わかりづらいかと思います。
本会員時の本人認証に揃える形で
・ログイン時の本人認証
のように変更したほうが、分かり易いかと思われます。

例：管理画面＞基本設定
![image1](https://user-images.githubusercontent.com/121000728/226268826-88d4c593-839d-4211-976a-3cf2361f264a.png)

例：管理画面＞会員編集
![image](https://user-images.githubusercontent.com/121000728/226282914-e1192233-107a-4299-9a73-b9844ce75c55.png)

**Comment by dotani1111** [comment]
明日プルリク作ります。

**Comment by chihiro-adachi** [comment]
#34 で対応
