### ISSUE TITLE
マジックナンバーを解消してほしい

### ISSUE THREAD

**Issue by kazuyoshikakihara** [EC-CUBE/TwoFactorAuthCustomer42#35]
ざっと見たところ、Service/CustomerTwoFactorAuthService.php の public function generateOneTimeToken(): string の中でトークンの桁数の6という数字が生で書かれていたり
https://github.com/EC-CUBE/TwoFactorAuthCustomer42/blob/e80dccae7df3a64bb251cc39fd4352694facfe09/Service/CustomerTwoFactorAuthService.php#L389

Entity/CustomerTrait.php の public function createDeviceAuthOneTimeToken(string $hashedOneTimePassword): void の中で+5 minsというトークンの有効期間の数字が生で書かれていたりします。
https://github.com/EC-CUBE/TwoFactorAuthCustomer42/blob/e80dccae7df3a64bb251cc39fd4352694facfe09/Entity/CustomerTrait.php#L89

何か適切な名前を付けてあげないと、後日コードを読み返すときに苦戦するかもです。

また、Entity/CustomerTrait.php の同箇所で$nowという変数が、$now->modify('+5 mins')されており、このため変数名は$nowでも最終的に実際は現在時刻よりも5分後の値が入ってしまっています。
今回のコードではこのままでも問題無いのですが、将来ここに誰かが何かを書き足す際に$nowが現在時刻だと思って使ってしまうと思わぬバグの原因になりかねません。
変数名を考え直すか、$now = new \DateTimeImmutable(); にして値が現在時刻から変わらないようにしたほうがよろしいかと存じます。

**Comment by KenTanaka** [comment]
@kazuyoshikakihara 
ありがとうございます！
確かにマジックナンバーは解消すべきですので

・トークン桁数 = 定数化
・+5 minsの部分は案件によって変更もある想定をしておくべきなのでCookie有効期限と同様設定ファイルへ外出し

として対応します。

**Comment by chihiro-adachi** [comment]
@kazuyoshikakihara 
レビューありがとうございました。
以下にて対応しています。
https://github.com/EC-CUBE/TwoFactorAuthCustomerSms42/pull/8
https://github.com/EC-CUBE/TwoFactorAuthCustomer42/pull/41
