### ISSUE TITLE
プラグイン設定：APIトークンのマスク処理見直し

### ISSUE THREAD

**Issue by KenTanaka** [EC-CUBE/TwoFactorAuthCustomer42#43]
・マスクされているinputのvalueにAPIトークンがそのまま出力されている為、
　EC-CUBE標準（会員パスワード/管理者メンバーパスワード）と同様の実装に修正する。

**Comment by sai-gillingham** [comment]
@KenTanaka

Issueを上げて頂いてありがとうございます。

APIトークンのマスク処理見直しましたので、ご確認お願いいたします。

https://github.com/EC-CUBE/TwoFactorAuthCustomer42/pull/49
