### ISSUE TITLE
二段階認証選択画面 - 直接URL入力すると設定完了後に再設定可能

### ISSUE THREAD

**Issue by KenTanaka** [EC-CUBE/TwoFactorAuthCustomer42#44]
・仕様として設定完了後の再設定はできないとしている為、設定済み認証方式にリダイレクトする。

**Comment by sai-gillingham** [comment]
@KenTanaka 


Issueを上げて頂いてありがとうございます。

お客様が二段階認証方式設定を完了した場合、
二段階認証選択画面を直接にアクセスしたら、
設定済み認証方式画面にリダイレクトするようにリダイレクトするように更新しました。

そのプルリクを作成しましたので、ご確認お願い出来ますか？

https://github.com/EC-CUBE/TwoFactorAuthCustomer42/pull/47
