### ISSUE TITLE
購入フローで二段階認証をスキップできる

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/TwoFactorAuthCustomer42#6]
以下手順で二段階認証をスキップできました。

- 会員登録し、本人認証まで完了する
- カートに商品をいれ、レジに進む
- ログインを行う
- 二段階認証の選択(SMS/APP)画面が表示される
- カートに戻る
- 再度レジに進む
- 注文画面が表示され、購入を完了できる

TwoFactorAuthCustomer42プラグインのみをインストールした環境です。
SMS/APPのプラグインはインストールしていないため、適切な環境ではないかもしれません。

**Comment by KenTanaka** [comment]
基本認証が必要なルートの設定漏れ

**Comment by chihiro-adachi** [comment]
修正確認しました
