### ISSUE TITLE
ツールチップのヘルプが表示されない

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/TwoFactorAuthCustomer42#8]
設定画面のツールチップが、カーソルを重ねても表示されない
<img width="489" alt="image" src="https://user-images.githubusercontent.com/8196725/223581442-9a2560b0-66f0-4944-b5bf-13f87790b0e9.png">

**Comment by KenTanaka** [comment]
ツールチップ文言をリソースに設定していない為。
取り急ぎ、

・本会員時の本人認証：本会員認証メールクリック後、SMSによる本人認証を実行します。
・2段階認証機能：ログイン時、SMSまたはアプリ認証による本人認証を実行します。

を設定します。

**Comment by chihiro-adachi** [comment]
#37 で対応
