### ISSUE TITLE
質問：会員編集画面の二段階認証時の電話番号とは何でしょうか？

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/TwoFactorAuthCustomer42#9]
この項目が何を指しているのかが少しわからず。。。
会員ごとに設定変更できる？
<img width="935" alt="image" src="https://user-images.githubusercontent.com/8196725/223581903-3ac749b1-26b2-4e5f-8bf8-172f764dd33e.png">

**Comment by dotani1111** [comment]
@chihiro-adachi 
本会員登録→ログイン時の2段階認証で、SMS認証した時の電話番号が保存されるようです。

**Comment by KenTanaka** [comment]
@chihiro-adachi 
@dotani1111  が記載してくれている通り、
　・会員登録時、本人認証が成功した場合の電話番号
　・ログイン二段階認証時、認証が成功した場合の電話番号
のいずれかを設定しています。

全会員通して、認証済み電話番号はユニーク（他の会員で同じ電話番号では認証不可）としています。

**Comment by chihiro-adachi** [comment]
ありがとうございます。理解しました。
